# Copyright 2026 DataRobot, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
import os
import re
from typing import Final

import pulumi
import pulumi_datarobot
from datarobot_pulumi_utils.pulumi import export
from datarobot_pulumi_utils.pulumi.stack import PROJECT_NAME
from datarobot_pulumi_utils.schema.apps import (
    ApplicationSourceArgs,
    CustomAppResourceBundles,
)
from datarobot_pulumi_utils.schema.exec_envs import RuntimeEnvironments

from . import project_dir, use_case
from .agent import agent_app_runtime_parameters
from .frontend_web import frontend_web
from .llm import app_runtime_parameters as llm_app_runtime_parameters
from .oauth import app_runtime_parameters as oauth_app_runtime_parameters

SESSION_SECRET_KEY: Final[str] = "SESSION_SECRET_KEY"
APPLICATION_MEMORY_SPACE_ID: Final[str] = "APPLICATION_MEMORY_SPACE_ID"
session_secret_key = os.environ.get(SESSION_SECRET_KEY)

required_key_scope_level: str = "admin"

EXCLUDE_PATTERNS = [
    re.compile(pattern)
    for pattern in [
        # Runtime parameters are passed via the API; uploading a metadata.yaml
        # alongside them is rejected by the platform. Also filters stale
        # metadata.yaml/metadata.yaml.jinja files generated by older versions
        # of this template.
        r"metadata\.yaml",
        r".*htmlcov/.*",
        r".*tests/.*",
        r".*\.coverage",
        r".*\.DS_Store",
        r".*\.pyc",
        r".*\.ruff_cache/.*",
        r".*\.venv/.*",
        r".*\.mypy_cache/.*",
        r".*__pycache__/.*",
        r".*\.pytest_cache/.*",
        r".*\.data/.*",
        r".*\.env",
        r".*\.uv/.*",
    ]
]


__all__ = [
    "fastapi_server_app",
    "fastapi_server_app_env_name",
    "fastapi_server_app_resource_name",
    "fastapi_server_app_runtime_parameters",
    "fastapi_server_app_source",
    "fastapi_server_application_path",
    "get_fastapi_server_app_files",
]


_TRUTHY_ENV_VALUES = frozenset({"1", "true", "yes"})


def env_flag_enabled(name: str) -> bool:
    """Return True when an environment variable is set to a truthy flag value."""
    return os.environ.get(name, "").strip().lower() in _TRUTHY_ENV_VALUES


def get_fastapi_server_app_files() -> list[tuple[str, str]]:
    # Get all files from application path, following symlinks
    # When we've upgraded to Python 3.13 we can use Path.glob(reduce_symlinks=True)
    # https://docs.python.org/3.13/library/pathlib.html#pathlib.Path.glob
    source_files = []
    for dirpath, dirnames, filenames in os.walk(
        fastapi_server_application_path, followlinks=True
    ):
        for filename in filenames:
            file_path = os.path.join(dirpath, filename)
            rel_path = os.path.relpath(file_path, fastapi_server_application_path)
            # Convert to forward slashes for Linux destination
            rel_path = rel_path.replace(os.path.sep, "/")
            source_files.append((os.path.abspath(file_path), rel_path))
    source_files = [
        (file_path, file_name)
        for file_path, file_name in source_files
        if not any(
            exclude_pattern.match(file_name) for exclude_pattern in EXCLUDE_PATTERNS
        )
    ]
    return source_files


# Start of Pulumi settings and application infrastructure
pulumi.export("SESSION_SECRET_KEY", session_secret_key)
session_secret_cred = pulumi_datarobot.ApiTokenCredential(
    f"Agentic Application Starter Session Secret Key [{PROJECT_NAME}]",
    args=pulumi_datarobot.ApiTokenCredentialArgs(
        api_token=str(session_secret_key),
    ),
)

# Memory space is consumed by the FastAPI application (session memory), not the agent
# deployment; expose it as Custom Application runtime parameters only.
memory_runtime_parameters = []
if env_flag_enabled("USE_APPLICATION_MEMORY_SPACE"):
    memory_space = pulumi_datarobot.MemorySpace(
        f"Application Memory Space ID [{PROJECT_NAME}]"
    )
    memory_runtime_parameters.extend(
        [
            pulumi_datarobot.ApplicationSourceRuntimeParameterValueArgs(
                key="USE_APPLICATION_MEMORY_SPACE",
                type="boolean",
                value="true",
            ),
            pulumi_datarobot.ApplicationSourceRuntimeParameterValueArgs(
                key=APPLICATION_MEMORY_SPACE_ID,
                type="string",
                value=memory_space.id,
            ),
        ]
    )
    _ = memory_space.id.apply(
        lambda memory_space_id: pulumi.info(
            f"Memory space configured for application: {memory_space_id}"
        )
    )
    export(APPLICATION_MEMORY_SPACE_ID, memory_space.id)
    pulumi.export(
        f"Application Memory Space ID [{PROJECT_NAME}]",
        memory_space.id,
    )

fastapi_server_app_env_name: str = "DATAROBOT_APPLICATION_ID"
fastapi_server_application_path = project_dir.parent / "fastapi_server"

fastapi_server_exec_env = os.environ.get(
    "DATAROBOT_DEFAULT_APPLICATION_EXECUTION_ENVIRONMENT", ""
).strip()
fastapi_server_base_environment_id = (
    fastapi_server_exec_env or RuntimeEnvironments.PYTHON_312_APPLICATION_BASE.value.id
)

fastapi_server_app_resource_name: str = f"Agentic Application Starter [{PROJECT_NAME}]"
fastapi_server_app_source_args = ApplicationSourceArgs(
    resource_name=fastapi_server_app_resource_name,
    base_environment_id=fastapi_server_base_environment_id,
).model_dump(mode="json", exclude_none=True)

fastapi_server_app_runtime_parameters: list[
    pulumi_datarobot.ApplicationSourceRuntimeParameterValueArgs
] = (
    agent_app_runtime_parameters
    + llm_app_runtime_parameters
    + memory_runtime_parameters
    + [
        parameter
        for parameter_group in [
            oauth_app_runtime_parameters,
        ]
        for parameter in parameter_group
    ]
    + [
        pulumi_datarobot.ApplicationSourceRuntimeParameterValueArgs(
            type="credential",
            key=SESSION_SECRET_KEY,
            value=session_secret_cred.id,
        ),
    ]
)

fastapi_server_app_source = pulumi_datarobot.ApplicationSource(
    # Custom change: Use frontend_web.stdout to ensure that the latest frontend build is complete
    # before creating the FastAPI application source.
    files=frontend_web.stdout.apply(lambda _: get_fastapi_server_app_files()),
    runtime_parameter_values=fastapi_server_app_runtime_parameters,
    resources=pulumi_datarobot.ApplicationSourceResourcesArgs(
        resource_label=CustomAppResourceBundles.CPU_XL.value.id,
    ),
    required_key_scope_level=required_key_scope_level,
    **fastapi_server_app_source_args,
)

fastapi_server_app = pulumi_datarobot.CustomApplication(
    resource_name=fastapi_server_app_resource_name,
    source_version_id=fastapi_server_app_source.version_id,
    use_case_ids=[use_case.id],
    allow_auto_stopping=True,
    resources=fastapi_server_app_source.resources,  # type: ignore[arg-type]
    required_key_scope_level=fastapi_server_app_source.required_key_scope_level,
    opts=pulumi.ResourceOptions(depends_on=[fastapi_server_app_source]),
)

pulumi.export(fastapi_server_app_env_name, fastapi_server_app.id)
pulumi.export(
    f"Agentic Starter [{PROJECT_NAME}]",
    fastapi_server_app.application_url,
)

DATABASE_URI: Final[str] = "DATABASE_URI"
database_uri = os.environ.get(
    DATABASE_URI, "sqlite+aiosqlite:////tmp/agent_app/.data/agent_app.db"
)

pulumi.export("DATABASE_URI", database_uri)

database_uri_cred = pulumi_datarobot.ApiTokenCredential(
    f"Agentic Application Starter Database URI [{PROJECT_NAME}]",
    args=pulumi_datarobot.ApiTokenCredentialArgs(
        api_token=str(database_uri),
    ),
)
